version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=rust
      - POSTGRES_PASSWORD=todoist
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./sql-init/:/docker-entrypoint-initdb.d/
volumes:
  postgres-db: